### ISSUE TITLE
MapaMental

### ISSUE THREAD

**Issue by ElisabetRD** [SistemasTecTlaxiaco/actividad-1-mapa-mental-ElisabetRD#1]
[ElisabetR_MapaPopplet.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-ElisabetRD/files/10679010/ElisabetR_MapaPopplet.pdf)

**Comment by Heidi-19** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
